### ISSUE TITLE
Connection fails after some time

### ISSUE THREAD

**Issue by jappish84** [dst6se/aquatemp#2]
Not sure if this issue should be reported here or over at https://github.com/sickidolderivative/aquatemp which is the repo I'm using, but I'm posting here since I can't find a way to report the issue there, and since that fork is based on this code. Please close if this issue isn't applicable here.

The integration works fine but seems to stop working and spits out an exception after a while. Not sure how to reproduce other than wait for it to stop working. Maybe you can find out more using the logs below:

`Logger: homeassistant.helpers.entity
Source: custom_components/aquatemp/climate.py:249
Integration: aquatemp (documentation)
First occurred: 18 september 2021 19:25:43 (2382 occurrences)
Last logged: 11:06:47

```
Update for climate.aquatemp fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aquatemp/climate.py", line 212, in update
    self.fetch_data()
  File "/config/custom_components/aquatemp/climate.py", line 249, in fetch_data
    t = requests.post(URL_GETDATABYCODE, headers = self._headers, data=json.dumps(data)).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
`

```
`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/aquatemp/climate.py:182
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:13:31 (2 occurrences)
Last logged: 11:06:18

[547392070944] Expecting value: line 1 column 1 (char 0)
[547402024992] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 434, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aquatemp/climate.py", line 182, in set_hvac_mode
    t = requests.post(URL_CONTROL, headers = self._headers, data=json.dumps(data)).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

```

**Comment by dst6se** [comment]
Hi , you should report it to https://github.com/sickidolderivative/aquatemp !
I think its the token thats not being refreshed !

**Comment by dst6se** [comment]
Sorry ! , the issue should be placed here due to sickidolderivative/aquatemp is a fork from this one !

**Comment by dst6se** [comment]
It should be reported to sickidolderivative

But sickidolderivative have to activate the issue tab on the fork
![Screenshot 2021-09-20 at 12 07 53](https://user-images.githubusercontent.com/56742601/133986011-e3abd5ba-3cdf-44dc-938f-70f30cca5d18.png)

**Comment by jappish84** [comment]
Thanks @dst6se. Will try and ping him

**Comment by radical-squared** [comment]
Thanks for letting me know. Just activated the issues tab and will look into it shortly.

**Comment by radical-squared** [comment]
The issue seems to be caused by an attempt to extract json from an erroneous server response. Hard to say if it's due to session expiry. I've introduced a number of checks throughout the code. Let's see if that helps.

**Comment by jappish84** [comment]
Awesome, appreciate the quick response!
Do I need to update the version number in manifest.json file when replacing the climate.py file?

**Comment by radical-squared** [comment]
Not sure about that. I don't and it works fine. :)
